#!/bin/bash
# Copyright (c) 2021, s.m.s, smart microwave sensors GmbH, Brunswick, Germany
#
# Setup script for CAN interface automatic configuration
# This script installs udev rules to automatically configure CAN interfaces

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UDEV_RULES_FILE="/etc/udev/rules.d/80-can-interface.rules"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}CAN Interface Setup for UMRR ROS2 Driver${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Check if running with sudo
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error: This script must be run with sudo${NC}"
    echo "Usage: sudo $0 [can_interface] [bitrate]"
    echo ""
    echo "Examples:"
    echo "  sudo $0                    # Uses default: can0 at 500000 bps"
    echo "  sudo $0 can0 500000        # Explicit values"
    echo "  sudo $0 can1 1000000       # Different interface and bitrate"
    exit 1
fi

# Parse arguments with defaults
CAN_INTERFACE="${1:-can0}"
CAN_BITRATE="${2:-500000}"

echo -e "Configuration:"
echo -e "  Interface: ${YELLOW}${CAN_INTERFACE}${NC}"
echo -e "  Bitrate:   ${YELLOW}${CAN_BITRATE}${NC} bps"
echo ""

# Create udev rules content
UDEV_RULES_CONTENT="# Automatically configure CAN interface for smartmicro radar
# Generated by UMRR ROS2 Driver setup script

# Rule for CAN interface: bring up with specified bitrate
SUBSYSTEM==\"net\", KERNEL==\"${CAN_INTERFACE}\", ACTION==\"add\", RUN+=\"/bin/sh -c 'ip link set ${CAN_INTERFACE} type can bitrate ${CAN_BITRATE} && ip link set ${CAN_INTERFACE} up'\"

# Rule to bring down cleanly on removal
SUBSYSTEM==\"net\", KERNEL==\"${CAN_INTERFACE}\", ACTION==\"remove\", RUN+=\"/sbin/ip link set ${CAN_INTERFACE} down\"
"

# Backup existing rules if present
if [ -f "$UDEV_RULES_FILE" ]; then
    echo -e "${YELLOW}Backing up existing udev rules...${NC}"
    cp "$UDEV_RULES_FILE" "${UDEV_RULES_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
fi

# Write udev rules
echo -e "${GREEN}Installing udev rules to ${UDEV_RULES_FILE}...${NC}"
echo "$UDEV_RULES_CONTENT" > "$UDEV_RULES_FILE"

# Set proper permissions
chmod 644 "$UDEV_RULES_FILE"

# Reload udev rules
echo -e "${GREEN}Reloading udev rules...${NC}"
udevadm control --reload-rules
udevadm trigger --subsystem-match=net

# Try to bring up the interface now if it exists
echo ""
echo -e "${GREEN}Attempting to bring up ${CAN_INTERFACE} now...${NC}"
if ip link show "$CAN_INTERFACE" &> /dev/null; then
    # Bring down first in case it's already configured
    ip link set "$CAN_INTERFACE" down 2>/dev/null || true

    # Configure and bring up
    if ip link set "$CAN_INTERFACE" type can bitrate "$CAN_BITRATE" && ip link set "$CAN_INTERFACE" up; then
        echo -e "${GREEN}✓ ${CAN_INTERFACE} is now up and configured${NC}"
        echo ""
        ip -details link show "$CAN_INTERFACE"
    else
        echo -e "${RED}✗ Failed to bring up ${CAN_INTERFACE}${NC}"
        echo -e "${YELLOW}The interface will be configured automatically when the hardware is detected${NC}"
    fi
else
    echo -e "${YELLOW}Interface ${CAN_INTERFACE} not found yet${NC}"
    echo -e "${YELLOW}It will be configured automatically when the hardware is connected${NC}"
fi

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Setup Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "The CAN interface will now be automatically configured when detected."
echo ""
echo -e "To verify the setup:"
echo -e "  ${YELLOW}ip link show ${CAN_INTERFACE}${NC}     # Check interface status"
echo -e "  ${YELLOW}candump ${CAN_INTERFACE}${NC}          # Monitor CAN traffic (requires can-utils)"
echo ""
echo -e "To uninstall:"
echo -e "  ${YELLOW}sudo rm ${UDEV_RULES_FILE}${NC}"
echo -e "  ${YELLOW}sudo udevadm control --reload-rules${NC}"
echo ""
